lesson3 task:1,2,3
js-tasks-ru/jsbasic-20240708-2_khlopovdima pull request #7
Opened 2024-07-10 09:42 UTC by Dima163163

2024-07-10 09:43 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-07-10 17:23 UTC, koalex requested changes
Тесты ОК, но задачи подразумевают решение другими методами (см. комментарии)

2024-07-10 17:23 UTC, koalex commented on 3-module/1-task/index.js
Попробуйте решить используя метод [map](https://learn.javascript.ru/array-methods#map)

2024-07-10 17:23 UTC, koalex commented on 3-module/2-task/index.js
Эту задачу нужно решить методом [filter](https://learn.javascript.ru/array-methods#filter)

2024-07-10 17:47 UTC, jsru-1 commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-07-10 17:50 UTC, Dima163163 commented on 3-module/1-task/index.js
Переделал на метод map

2024-07-10 17:51 UTC, Dima163163 commented on 3-module/2-task/index.js
Переделал на метод filter

2024-07-11 02:53 UTC, koalex approved these changes

2024-07-11 02:54 UTC, merged